name: CO2
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch
  - torchmetrics
  - torchvision
  - tensorflow
  - keras
  - scikit-learn
  - ipykernel
  - notebook
  - tqdm
  - seaborn
