name: CO2
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - torchmetrics
  - keras
  - scikit-learn
  - ipykernel
  - notebook
  - tqdm
  - seaborn
  - tensorflow
  - pip:
      - torch torchvision --index-url https://download.pytorch.org/whl/cu118
